# Generated by Django 3.2.5 on 2022-01-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
